### PR TITLE
Constrain variable names

### LINKED ISSUE #38: Build a migration for variable names and option values
For interoperability variable names, and categorical/ordinal option values must be constrained.

There needs to be a migration to update older protocols.

- properties to respect the constraint:
  `/^[a-zA-Z0-9._\\-:]*$/`
- update all node/edge/ego **variable names**, e.g.
  `codebook.node[uid].variables[variableUid].name`
- update all categorical/ordinal **options values**, e.g.
  `codebook.node[uid].variables[variableUid].options[].value`
- Should also include making stage name unique: https://github.com/codaco/Architect/issues/650

### PR DESCRIPTION
**Pull request by wwqrd**
Update validation to constrain variable names in schema version 4.

- Variable names are constrained by the nmtoken rules
- Option values are constrained by the nmtoken rules
- Entity names are constrained by the nmtoken rules
- Migration for v4 of the schema has been added
- Helper function for getting the migration notes (which are a new feature)

Resolves https://github.com/codaco/protocol-validation/issues/38

### CODE REVIEW

**Review by jthrilly — CHANGES_REQUESTED** [review]
Working great!

A couple of changes:
- I added some styling for the migration notes section. Wasn't sure where to put it, so can you move them to where you think is most appropriate?
- We discussed linking to the documentation in the migration dialog, but I didn't see this implemented. I added a link to the dialog, but it doesn't work. I suspect it needs some electron special sauce, but I didn't want to make that change myself. Can you look at it?
- It occurred to me that external data already loaded won't be updated or invalidated by the migration. I don't think there is much of anything we can do it about, but I wanted to note it here in case you can think of anything.
- This bug has been introduced: https://github.com/codaco/Architect/issues/656

**Comment by jthrilly** [comment]
Once the above is resolved, feel free to merge the protocol validation branch and update the ref here.

We then need a corresponding PR in NC, which will need to mark protocol versions prior to 4 as obsolete rather than outdated.

**Comment by jthrilly** [comment]
>It occurred to me that external data already loaded won't be updated or invalidated by the migration. I don't think there is much of anything we can do it about, but I wanted to note it here in case you can think of anything.

On this, if there are no better ideas, can we add an additional bullet point to the migration notes:

- **NOTE:** If you are using external network data, you must ensure that you update your column headings manually to meet the same requirements regarding variable names outlined above. See our revised [documentation on variable naming](https://documentation.networkcanvas.com/docs/key-concepts/variable-naming/).

The link in the note above is just going to a blank page for now.

**Comment by wwqrd** [comment]
> We discussed linking to the documentation in the migration dialog, but I didn't see this implemented. I added a link to the dialog, but it doesn't work. I suspect it needs some electron special sauce, but I didn't want to make that change myself. Can you look at it?

I had thought this would go in the notes, since it's markdown?

Screenshot 2020-07-01 at 10 30 03

I'm not sure about this, I'd intentionally left out commas since I was concerned it might be confusing (is comma one of the characters?) - I know that it's obvious to us.

**Comment by wwqrd** [comment]
> It occurred to me that external data already loaded won't be updated or invalidated by the migration. I don't think there is much of anything we can do it about, but I wanted to note it here in case you can think of anything.

We could check that within NC, it isn't something that's handled by this submodule at the moment - but could potentially port some of the code from Architect.

**Comment by wwqrd** [comment]
> We could check that within NC, it isn't something that's handled by this submodule at the moment - but could potentially port some of the code from Architect.

I've extracted the relevant code here so that it can be referenced in NC

**Pull request merged**
